site_name: Armada Public API
docs_dir: src
site_dir: docs
theme:
  name: material
  favicon: img/favicon.png
  logo: img/favicon.png
copyright: Copyright &copy; 2016 - 2024 Armada Delivery Solutions
extra:
  generator: false
nav:
  - 'index.md'
  - 'authentication.md'
  - 'estimation.md'
  - 'branches_management.md'
  - 'order_placement.md'
  - 'webhooks.md'
  - 'sandbox_access.md'

