name: Update Notion status
on:
  pull_request:
    types: [review_requested]
jobs:
  update_status:
    runs-on: ubuntu-latest
    steps:
      - name: Update Notion status
        uses: armadadelivery/update-task-status@v1.3
        with:
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          notion_auth_token: ${{ secrets.NOTION_AUTH_TOKEN }}
          notion_status: "🔎 In Review"
          branch: ${{ github.event.pull_request.head.ref }}
